### ISSUE TITLE
we're being flagged by stand users

### ISSUE THREAD

**Issue by mikedrugs** [xesdoog/YimActions#40]
so when you play animations with props enabled while close to a stand user, they get spammed notifications like you are trying to crash them, this sucks tbh because they might think we are genuinely being malicious, is this stands fault or yim's method to spawn props?

**Comment by xesdoog** [comment]
This has been going on since a few game updates ago. I don't know what exactly happened but almost every menu spawning props now triggers that. I've had my log get filled with object crash notifications just because a friend using PhantomX was trying to build a house with spawned objects. I've also had a few Stand users trigger that notification for me but they were simply sitting on chairs in car meets.

**Comment by xesdoog** [comment]
@mikedrugs 
Hey mike,

Is the issue still happening to you? I've been testing a few things and so far only object spawners both on my end and on a friend's end (using a different menu) triggered the notification for both of us on some objects. I'll see if I can pinpoint which objects are triggering it but in the meantime I would like to make sure that YimActions is working properly for you because I've implemented an improved version of it into a new script I'm working on.

Thanks.
